---
- name: Install packages required for adding the apt repository
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gpg

- name: postgresql 11 tasks
  when: postgres_major_version == 11
  block:
    - name: Add an apt signing key, uses whichever key is at the URL
      apt_key:
        url: "{{ item }}"
        state: present
      with_items:
        - https://www.postgresql.org/media/keys/ACCC4CF8.asc

    - name: Install apt repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main

- name: postgresql 10 tasks
  when: postgres_major_version == 10
  block:
    - name: Add an apt signing key, uses whichever key is at the URL
      apt_key:
        url: "{{ item }}"
        state: present
      with_items:
        - https://www.postgresql.org/media/keys/ACCC4CF8.asc

    - name: Install apt repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
