---
- name: Install postgresql yum repository
  package:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install packages required for CentOS 8
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - glibc-langpack-en
  when: ansible_distribution_major_version == "8"

- name: Disable the built-in PostgreSQL module
  command: dnf -qy module disable postgresql
  args:
    warn: false  # set warn=false to prevent warning
  when: ansible_distribution_major_version == "8"
