---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/yaml-lint.yml .
  ansible-lint -c molecule/ansible-lint.yml .
  flake8
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: false
  options:
    vvv: false
  playbooks:
    converge: "converge-${MOLECULE_PLAYBOOK:-15}.yml"
    verify: "verify-${MOLECULE_PLAYBOOK:-15}.yml"
scenario:
  name: default
verifier:
  name: ansible
