---
- name: Converge
  hosts: all
  become: true

  vars:
    - postgres_major_version: 12
    - postgres_listen_addresses: "*"
    - postgres_client_auth:
        - type: host
          database: all
          user: all
          address: 0.0.0.0/0
          method: md5

  roles:
    - role: ansible-role-postgres

  post_tasks:
    - name: Test if the postgres 12 is running
      shell: psql -c "SELECT version();"
      args:
        executable: /bin/bash
      register: postgresql_version
      become: true
      become_user: postgres
      become_method: sudo
      changed_when: false
      failed_when:
        - '"PostgreSQL 12" not in postgresql_version.stdout'
