---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Test if the postgres 10 is running
      shell: psql -c "SELECT version();"
      args:
        executable: /bin/bash
      register: postgresql_version
      become: true
      become_user: postgres
      become_method: sudo
      changed_when: false
      failed_when:
        - '"PostgreSQL 10" not in postgresql_version.stdout'
