---
name: Molecule Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro: ['centos7', 'centos8', 'ubuntu1804']
        molecule_playbook: ['playbook-10.yml', 'playbook-11.yml', 'playbook-12.yml']
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule docker
      - name: Test with molecule
        run: |
          molecule test --all
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.molecule_playbook }}
